(()=>{'use strict';
 const data=[{"name": "Créer des sites web 3D animés", "lead": "Transformer un brief en une expérience web immersive, fluide et accessible.", "project": "Un site 3D publié, accompagné d’un storyboard, d’assets optimisés, de tests mobile et d’un dossier de livraison.", "forwho": "Créatifs, designers, profils digitaux et entrepreneurs prêts à développer des compétences web.", "prereq": "Les bases HTML/CSS/JavaScript sont abordées dans un parcours de fondations ; la pratique est indispensable.", "tools": "HTML, CSS, JavaScript, Git, Three.js, React Three Fiber, Blender, GSAP.", "url": "formations/sites-web-3d.html"}, {"name": "Créer des agents personnalisés", "lead": "Concevoir un agent défini par un rôle précis, connecté à des outils et contrôlé par des validations.", "project": "Un agent fonctionnel documenté, avec permissions, tests, traces, critères d’évaluation et règles d’escalade.", "forwho": "Professionnels et entrepreneurs, avec une voie visuelle et une voie technique.", "prereq": "Deux voies prévues : no-code/low-code et SDK ; aucune compétence de programmation n’est nécessaire pour le premier parcours.", "tools": "Instructions, bases documentaires, APIs, Make AI Agents ou équivalent, Agents SDK.", "url": "formations/agents-personnalises.html"}, {"name": "Automatiser une tâche fastidieuse", "lead": "Transformer une tâche répétitive en workflow robuste, mesurable et maintenable.", "project": "Une automatisation opérationnelle, testée sur les erreurs, avec mesure du gain et documentation de reprise.", "forwho": "Personnes confrontées à des tâches répétitives dans leur travail, avec ou sans expérience des automatisations.", "prereq": "Aucun langage de programmation imposé ; savoir décrire son processus et manipuler des données simples aide.", "tools": "n8n, Make, APIs, webhooks, JSON, journaux d’exécution.", "url": "formations/automatiser-tache.html"}, {"name": "Simplifier les processus du quotidien", "lead": "Utiliser l’IA pour comprendre, rédiger, comparer, planifier et décider sans lui déléguer son jugement.", "project": "Un Playbook IA personnel avec 5 à 10 méthodes de travail réutilisables et leurs points de contrôle.", "forwho": "Débutants ou utilisateurs intermédiaires souhaitant intégrer l’IA à leurs tâches professionnelles courantes.", "prereq": "Aucun prérequis technique ; accès à un assistant IA capable de traiter du texte, et idéalement des fichiers.", "tools": "Assistants IA, documents, modèles de prompts, tableaux simples et méthodes de vérification.", "url": "formations/ia-au-quotidien.html"}];
 const buttons=[...document.querySelectorAll('[data-orientation]')];
 const title=document.getElementById('recTitle'),desc=document.getElementById('recText'),link=document.getElementById('recLink');
 buttons.forEach(btn=>btn.addEventListener('click',()=>{
  const i=Number(btn.dataset.orientation);if(!data[i])return;
  buttons.forEach(other=>other.setAttribute('aria-pressed',String(other===btn)));
  title.textContent=data[i].name;desc.textContent=data[i].lead+' '+data[i].project;
  link.href=data[i].url;
 }));
 document.getElementById('exportComparison').addEventListener('click',()=>{
  const content=['IAGILE — COMPARATIF DES 4 PARCOURS','Programmes en préparation — tarifs et inscriptions non définis','',...data.flatMap(c=>[c.name,'Objectif : '+c.lead,'Public : '+c.forwho,'Prérequis : '+c.prereq,'Outils : '+c.tools,'Projet final : '+c.project,''])].join('\n');
  const file=new Blob([content],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download='iagile-comparatif-formations.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);
 });
})();