/* IAgile V18 — seven practical modules. Offline learner practice, not AI-generated marking. */
(()=>{'use strict';
const KEY='iagile-v18-modules-2026-10';
const V17KEY='iagile-v17-pilot-2026-10';
const numbers=[2,3,4,5,6,7,8];
const moduleNames={2:'Recherche',3:'Rédaction',4:'Documents',5:'Décisions',6:'Organisation',7:'Handoff',8:'Confidentialité'};
const fields={};
for(const n of numbers){fields[n]=[...document.querySelectorAll(`#form-${n} [data-field]`)].map(el=>el.dataset.field)}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const empty=()=>({version:1,work:{},complete:{},updatedAt:''});
function str(value,max=1600){return typeof value==='string'?value.slice(0,max):''}
function sanitize(raw){const base=empty();if(!raw||typeof raw!=='object'||raw.version!==1)return base;for(const n of numbers){const r=raw.work?.[n]||{};base.work[n]={};for(const k of fields[n])base.work[n][k]=str(r[k]);base.work[n].check0=r.check0===true;base.work[n].check1=r.check1===true;base.complete[n]=raw.complete?.[n]===true&&fields[n].every(k=>base.work[n][k].trim().length>=12)&&base.work[n].check0&&base.work[n].check1}return base}
let state=empty(),stored=true;
try{let data=localStorage.getItem(KEY);if(data)state=sanitize(JSON.parse(data))}catch(e){stored=false}
const getRecord=n=>state.work[n]||(state.work[n]={});
let toastTimer;
function toast(message){let box=$('#toast');box.textContent=message;box.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.hidden=true,4200)}
function save(){state.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){if(stored){stored=false;toast('Sauvegarde locale impossible. Exportez votre travail régulièrement.')}}refresh()}
function refresh(){let done=numbers.filter(n=>state.complete[n]===true).length;$('#count').textContent=`${done} / 7`;$('#progress').setAttribute('aria-valuenow',String(done));$('#fill').style.width=(done/7*100).toFixed(1)+'%';for(const n of numbers){const s=$(`[data-check="${n}"]`);s.textContent=state.complete[n]?'✓':'↗';s.classList.toggle('done',state.complete[n]===true)}$('#finalCount').textContent=done+'/7';$('#finalStatus').textContent=done===7?'Les 7 livrables sont documentés. Une revue pédagogique reste nécessaire.':'Il reste '+(7-done)+' atelier'+(7-done>1?'s':'')+' à documenter. Aucun score pédagogique n’est attribué.';let book='—';try{let data=JSON.parse(localStorage.getItem(V17KEY)||'{}');if(data.version===1&&Array.isArray(data.book))book=Math.min(data.book.length,10)+'/5 min.'}catch(e){}$('#legacyBook').textContent=book}
function hydrateForm(n){const row=getRecord(n),form=$('#form-'+n);for(const k of fields[n]){form.querySelector(`[data-field="${k}"]`).value=row[k]||''}form.querySelector('[data-verify="0"]').checked=row.check0===true;form.querySelector('[data-verify="1"]').checked=row.check1===true;const f=$('#feedback-'+n);f.hidden=true;}
function navigate(section,changeHash=true){const valid=section==='final'||numbers.includes(Number(section));if(!valid)return;const isFinal=section==='final';$('#intro').hidden=true;for(const n of numbers){const el=$(`#module-${n}`);el.hidden=isFinal||n!==Number(section)}$('#final').hidden=!isFinal;const active=isFinal?'final':String(section);for(const button of $$('.mod-nav button')){const selected=button.dataset.module===active;button.classList.toggle('active',selected);button.setAttribute('aria-current',selected?'step':'false')}$('#finalLink').classList.toggle('active',isFinal);$('#counter').textContent=isFinal?'PROJET FINAL':'MODULE '+String(section).padStart(2,'0')+' / 08';if(changeHash)history.replaceState(null,'','#'+active);window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});const heading=isFinal?$('#final h1'):$(`#h${section}`);heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});}
for(const n of numbers){const form=$('#form-'+n);form.addEventListener('input',event=>{const el=event.target,row=getRecord(n);if(el.dataset.field)row[el.dataset.field]=str(el.value);else if(el.dataset.verify!==undefined)row['check'+el.dataset.verify]=el.checked;if(state.complete[n]){state.complete[n]=false;$('#feedback-'+n).hidden=true}save()});form.addEventListener('change',event=>{const el=event.target;if(el.dataset.verify!==undefined){getRecord(n)['check'+el.dataset.verify]=el.checked;if(state.complete[n])state.complete[n]=false;save()}});form.addEventListener('submit',event=>{event.preventDefault();const row=getRecord(n);let missing=fields[n].filter(k=>(row[k]||'').trim().length<12),allChecked=row.check0&&row.check1;let fb=$('#feedback-'+n);fb.hidden=false;if(missing.length||!allChecked){state.complete[n]=false;fb.className='feedback error';fb.textContent='Complétez chaque livrable avec au moins 12 caractères et cochez uniquement les vérifications réellement effectuées.';save();return;}state.complete[n]=true;fb.className='feedback';fb.textContent='Atelier documenté. Cette étape confirme votre auto-déclaration, sans correction automatique ni certification.';save();toast('Atelier enregistré dans votre progression locale.')});hydrateForm(n)}
$$('[data-module]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.module)));
$$('[data-next]').forEach(el=>el.addEventListener('click',()=>{let next=Number(el.dataset.next)+1;navigate(next<=8?next:'final')}));
$('#finalLink').addEventListener('click',e=>{e.preventDefault();navigate('final')});
$$('[data-copy]').forEach(el=>el.addEventListener('click',async()=>{const text=$('#template-'+el.dataset.copy).textContent;try{await navigator.clipboard.writeText(text);toast('Modèle copié. Adaptez-le à votre tâche.')}catch(e){toast('Copie automatique indisponible. Sélectionnez le texte dans le bloc.')}}));
addEventListener('hashchange',()=>{const key=location.hash.slice(1);if(key==='final'||numbers.includes(Number(key)))navigate(key,false)});
function download(name,content,mime){const blob=new Blob([content],{type:mime+';charset=utf-8'});const uri=URL.createObjectURL(blob),a=document.createElement('a');a.href=uri;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(uri),2500)}
function asMarkdown(){let lines=['# IAgile V18 — Dossier de pratique','',`Export réalisé : ${new Date().toISOString()}`,'','_Travail d’auto-évaluation non corrigé par une IA ou un formateur._',''];for(const n of numbers){lines.push(`## Module ${n} — ${moduleNames[n]}`,'',`Atelier déclaré réalisé : ${state.complete[n]?'Oui':'Non'}`,'');for(const k of fields[n]){lines.push(`### ${k}`,(state.work[n]?.[k]||'À compléter'),'')}lines.push('Vérifications déclarées : '+(state.work[n]?.check0&&state.work[n]?.check1?'Deux cochées':'Incomplètes'),'')}return lines.join('\n')}
$('#export').addEventListener('click',()=>{download('iagile-v18-sauvegarde.json',JSON.stringify(state,null,2),'application/json');toast('Sauvegarde V18 téléchargée.')});
$('#exportNotes').addEventListener('click',()=>{download('iagile-v18-livrables.md',asMarkdown(),'text/markdown');toast('Dossier de pratique téléchargé.')});
$('#downloadFinal').addEventListener('click',()=>$('#exportNotes').click());
$('#import').addEventListener('click',()=>$('#importFile').click());
$('#importFile').addEventListener('change',async e=>{let file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>1_000_000){toast('Le fichier doit peser moins de 1 Mo.');return}try{let parsed=JSON.parse(await file.text());if(parsed?.version!==1||typeof parsed.work!=='object'||typeof parsed.complete!=='object'||Array.isArray(parsed.work))throw Error('invalid');if(!confirm('Remplacer les ateliers V18 actuels par ce fichier ?'))return;state=sanitize(parsed);for(const n of numbers)hydrateForm(n);save();navigate('2');toast('Sauvegarde V18 importée.')}catch(error){toast('Sauvegarde V18 invalide ou illisible.')}});
const dialog=$('#confirmReset');$('#reset').addEventListener('click',()=>dialog.showModal());$('#cancelReset').addEventListener('click',()=>dialog.close());$('#confirmResetButton').addEventListener('click',()=>{state=empty();try{localStorage.removeItem(KEY)}catch(e){}for(const n of numbers)hydrateForm(n);save();dialog.close();navigate('2');toast('Ateliers V18 réinitialisés.')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&dialog.open)dialog.close()});
refresh();const start=location.hash.slice(1);navigate(start==='final'||numbers.includes(Number(start))?start:'2',false);
if(!stored)toast('Stockage local indisponible : exportez régulièrement vos travaux.');
window.IAgileV18={getState:()=>structuredClone(state),navigate,modules:numbers.slice(),version:'18-pilote'};
})();
