/* IAgile V17 pilot. Local-only learning experience; self-checks are not AI grading. */
(()=>{'use strict';
const KEY='iagile-v17-pilot-2026-10';
const views=['accueil','defi','diagnostic','methode','playbook'];
const profiles={organiser:'Votre premier exemple : préparer une réunion et transformer des notes en liste d’actions vérifiées.',produire:'Votre premier exemple : transformer des notes internes en message professionnel, avec relecture humaine.',analyser:'Votre premier exemple : comparer deux options en séparant faits vérifiés, hypothèses et critères.',coordonner:'Votre premier exemple : préparer un brief de projet que quelqu’un peut reprendre sans explication orale.'};
const categories=['recherche','redaction','documents','organisation','decision','autre'];
const bookFields=['name','trigger','goal','context','steps','prompt','checks','limits','tools','measure'];
const fieldLabels={name:'Nom du processus',trigger:'Déclencheur',goal:'Objectif',context:'Contexte à fournir',steps:'Méthode pas à pas',prompt:'Instruction réutilisable',checks:'Vérifications',limits:'Quand ne pas l’utiliser',tools:'Outil principal et alternative',measure:'Mesure avant / après'};
const mFields=['mContext','mGoal','mInput','mConstraints','mSuccess','mFormat'];
const cFields=['challengeTask','challengeGoal','challengeBefore','challengePrep','challengeGenerate','challengeVerify','challengeCorrect','challengeQuality','challengeDecision','challengeSafe'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const initial=()=>({version:1,profile:'',depth:'essentiel',completed:{accueil:false,defi:false,diagnostic:false,methode:false},challenge:{},diagnostic:{tasks:[{name:'',minutes:''},{name:'',minutes:''},{name:'',minutes:''}],human:'',safe:false},method:{},book:[],updatedAt:null});
const str=(v,max=2200)=>typeof v==='string'?v.slice(0,max):'';
const sanitizeEntry=e=>Object.fromEntries([...bookFields.map(k=>[k,str(e?.[k])]),['category',categories.includes(e?.category)?e.category:'autre'],['tested',e?.tested===true],['source',e?.source==='challenge'?'challenge':'manual']]);
const hydrate=s=>{const next=initial();if(!s||typeof s!=='object'||s.version!==1)return next;next.profile=Object.hasOwn(profiles,s.profile)?s.profile:'';next.depth=s.depth==='approfondi'?'approfondi':'essentiel';for(const k of ['accueil','defi','diagnostic','methode'])next.completed[k]=s.completed?.[k]===true;
 for(const k of cFields){next.challenge[k]=k==='challengeSafe'?s.challenge?.[k]===true:str(s.challenge?.[k],900)};
 next.diagnostic.tasks=[0,1,2].map(i=>({name:str(s.diagnostic?.tasks?.[i]?.name,180),minutes:str(s.diagnostic?.tasks?.[i]?.minutes,10)}));next.diagnostic.human=str(s.diagnostic?.human,800);next.diagnostic.safe=s.diagnostic?.safe===true;
 for(const k of mFields.concat(['mCheckFactual','mCheckScope','mCheckPrivacy']))next.method[k]=k.startsWith('mCheck')?s.method?.[k]===true:str(s.method?.[k],800);
 next.book=Array.isArray(s.book)?s.book.slice(0,10).map(sanitizeEntry):[];return next;};
let storageAvailable=true;
let state=initial();try{const saved=localStorage.getItem(KEY);if(saved)state=hydrate(JSON.parse(saved));}catch(e){storageAvailable=false;}
function save(){state.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){if(storageAvailable){storageAvailable=false;toast('Le stockage local est indisponible. Exportez vos réponses pour les conserver.');}}renderProgress();}
let toastTimeout;
function toast(message){const el=$('#toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.hidden=true,4300)}
function renderProgress(){const n=['defi','diagnostic','methode'].filter(k=>state.completed[k]).length+(state.book.some(e=>e.name.trim()&&e.trigger.trim())?1:0);$('#progressRatio').textContent=n+'/4';$('#progressBarFill').style.width=(n/4*100)+'%';$('#progressBar').setAttribute('aria-valuenow',String(n));for(const key of views){const el=$(`[data-done="${key}"]`);if(!el)continue;const done=key==='playbook'?state.book.some(e=>e.name.trim()&&e.trigger.trim()):key==='accueil'?Boolean(state.profile):Boolean(state.completed[key]);el.classList.toggle('done',done);el.textContent=done?'✓':'↗';}$('#bookCount').textContent=state.book.length+' / 5 minimum';$('#bookStatus').textContent=state.book.length>=5?'Nombre minimal de fiches atteint : ajoutez preuves et validations avant tout projet final.':'Encore '+(5-state.book.length)+' fiche'+(5-state.book.length>1?'s':'')+' pour le minimum du projet final complet.';}
function navigate(key,updateHash=true){if(!views.includes(key))return;for(const k of views){const e=$('#view-'+k);e.hidden=k!==key;e.classList.toggle('is-visible',k===key)}for(const e of $$('.course-link')){const active=e.dataset.view===key;e.classList.toggle('is-active',active);if(active)e.setAttribute('aria-current','step');else e.removeAttribute('aria-current')};$('#sectionCounter').textContent=String(views.indexOf(key)+1).padStart(2,'0')+' — 05';if(updateHash){history.replaceState(null,'','#'+key)}window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});const h=$('#view-'+key+' h1');if(h){h.setAttribute('tabindex','-1');h.focus({preventScroll:true})}renderProgress();}
$$('[data-view]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.view)));$$('[data-next]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.next)));addEventListener('hashchange',()=>{const view=location.hash.slice(1);if(views.includes(view))navigate(view,false)});
function renderProfile(){$$('[data-profile]').forEach(e=>{const on=e.dataset.profile===state.profile;e.classList.toggle('is-selected',on);e.setAttribute('aria-pressed',String(on))});$('#depth').value=state.depth;$('#profileNote').textContent=profiles[state.profile]||'Choisissez un domaine pour recevoir un exemple adapté à votre quotidien.';$('#diagnosticExtra').hidden=state.depth!=='approfondi';$('#methodeExtra').hidden=state.depth!=='approfondi';}
$$('[data-profile]').forEach(el=>el.addEventListener('click',()=>{state.profile=el.dataset.profile;state.completed.accueil=true;renderProfile();save()}));$('#depth').addEventListener('change',e=>{state.depth=e.target.value;renderProfile();save()});$('#startPilot').addEventListener('click',()=>{if(!state.profile){toast('Choisissez une priorité pour personnaliser votre départ.');return}state.completed.accueil=true;save();navigate('defi')});
const numeric=id=>{const s=$(id).value.trim();if(s==='')return null;const n=Number(s);return Number.isFinite(n)&&n>=0&&n<=600?n:null};
function updateGain(){const b=numeric('#challengeBefore'),parts=['#challengePrep','#challengeGenerate','#challengeVerify','#challengeCorrect'].map(numeric);const complete=parts.every(x=>x!==null);$('#timeTotal').textContent=complete?parts.reduce((a,b)=>a+b,0)+' min':'—';$('#timeNet').textContent=complete&&b!==null?(b-parts.reduce((a,b)=>a+b,0))+' min':'—';$('#timeNet').style.color=complete&&b!==null&&b-parts.reduce((a,b)=>a+b,0)<0?'#FFBFB8':'#FFFFFF';}
for(const id of cFields){const e=$('#'+id);e.type==='checkbox'?e.checked=state.challenge[id]===true:e.value=state.challenge[id]||'';e.addEventListener('input',()=>{state.challenge[id]=e.type==='checkbox'?e.checked:e.value;state.completed.defi=false;$('#challengeFeedback').hidden=true;save();updateGain()});e.addEventListener('change',()=>{state.challenge[id]=e.type==='checkbox'?e.checked:e.value;state.completed.defi=false;$('#challengeFeedback').hidden=true;save();updateGain()});}updateGain();
function showFeedback(sel,message,error=false){const el=$(sel);el.hidden=false;el.classList.toggle('error',error);el.textContent=message;}
$('#challengeForm').addEventListener('submit',e=>{e.preventDefault();const s=state.challenge;const parts=['challengePrep','challengeGenerate','challengeVerify','challengeCorrect'].map(k=>numeric('#'+k));const b=numeric('#challengeBefore');if(!str(s.challengeTask).trim()||!str(s.challengeGoal).trim()||b===null||b<1||parts.some(n=>n===null)||!s.challengeQuality||!s.challengeDecision||s.challengeSafe!==true){showFeedback('#challengeFeedback','Complétez la tâche, son objectif, toutes les durées, la qualité, la décision et la vérification des données.',true);return}
 const total=parts.reduce((a,b)=>a+b,0),gain=b-total;state.completed.defi=true;let note=gain>=0?`Vous avez mesuré ${gain} minute(s) de gain net.`:`Votre essai demande ${Math.abs(gain)} minute(s) de plus que d'habitude : c'est un résultat utile à analyser.`;if(s.challengeQuality!=='oui')note+=' La qualité n’est pas encore satisfaisante : corrigez ou simplifiez avant de conserver la méthode.';if(s.challengeDecision==='conserver'&&s.challengeQuality!=='oui')note+=' Votre choix « conserver » mérite donc d’être réévalué.';
 const bookSeed={name:s.challengeTask,goal:s.challengeGoal,measure:`Temps habituel : ${b} min. Total : ${total} min. Gain net : ${gain} min. Décision : ${s.challengeDecision}.`,category:'autre',tested:true,source:'challenge'};const existing=state.book.findIndex(v=>v.source==='challenge');if(existing>=0){Object.assign(state.book[existing],bookSeed)}else if(state.book.length<10){state.book.push(sanitizeEntry({...bookSeed,trigger:'Lorsque cette tâche revient',checks:'Vérifier toutes les informations importantes avant utilisation.'}))};save();renderBook();showFeedback('#challengeFeedback',note+' Une première fiche a été créée dans votre Playbook ; vous pouvez maintenant la compléter.');});
function renderDiagnostic(){const wrap=$('#diagnosticTasks');wrap.replaceChildren();state.diagnostic.tasks.forEach((task,i)=>{const box=document.createElement('div');box.className='task-card';box.innerHTML=`<strong>PROCESSUS ${String(i+1).padStart(2,'0')}</strong><div class="task-grid"><label class="field">Tâche récurrente <span class="required">*</span><input type="text" maxlength="180" data-task-name="${i}" placeholder="Ex. organiser une semaine de travail" required></label><label class="field">Durée actuelle (min)<input type="number" min="0" max="600" data-task-time="${i}" placeholder="35" inputmode="numeric"></label></div>`;box.querySelector('[data-task-name]').value=task.name;box.querySelector('[data-task-time]').value=task.minutes;wrap.append(box)})};renderDiagnostic();
$('#diagnosticTasks').addEventListener('input',e=>{const i=e.target.dataset.taskName??e.target.dataset.taskTime;if(i===undefined)return;state.diagnostic.tasks[Number(i)][e.target.hasAttribute('data-task-name')?'name':'minutes']=e.target.value;state.completed.diagnostic=false;$('#diagnosticFeedback').hidden=true;save()});$('#diagnosticHuman').value=state.diagnostic.human;$('#diagnosticRisk').checked=state.diagnostic.safe;$('#diagnosticHuman').addEventListener('input',e=>{state.diagnostic.human=e.target.value;state.completed.diagnostic=false;$('#diagnosticFeedback').hidden=true;save()});$('#diagnosticRisk').addEventListener('change',e=>{state.diagnostic.safe=e.target.checked;state.completed.diagnostic=false;$('#diagnosticFeedback').hidden=true;save()});
$('#diagnosticForm').addEventListener('submit',e=>{e.preventDefault();const d=state.diagnostic;const names=d.tasks.map(t=>t.name.trim());if(names.some(n=>n.length<5)||new Set(names.map(n=>n.toLowerCase())).size<3||d.human.trim().length<12||!d.safe){showFeedback('#diagnosticFeedback','Décrivez trois tâches différentes et une vérification humaine explicite (12 caractères minimum), puis confirmez le cadre à faible risque.',true);return}state.completed.diagnostic=true;save();showFeedback('#diagnosticFeedback','Diagnostic enregistré. Vos trois processus sont identifiés : vous pouvez désormais construire une instruction réutilisable dans le module 1.');});
function assemblePrompt(){const v=state.method;return ['CONTEXTE', 'OBJECTIF','ENTRÉES','CONTRAINTES','CRITÈRES DE RÉUSSITE','FORMAT ATTENDU'].map((title,i)=>`${title}\n${str(v[mFields[i]],800).trim()||'[À compléter]'}`).join('\n\n')+'\n\nVÉRIFICATION : Signale les informations manquantes ; n’invente pas de faits ou d’engagements. Je valide le résultat avant de l’utiliser.';}
function renderPrompt(){$('#promptPreview').textContent=assemblePrompt();}
for(const id of mFields.concat(['mCheckFactual','mCheckScope','mCheckPrivacy'])){const e=$('#'+id);if(e.type==='checkbox')e.checked=state.method[id]===true;else e.value=state.method[id]||'';const fn=()=>{state.method[id]=e.type==='checkbox'?e.checked:e.value;state.completed.methode=false;$('#methodFeedback').hidden=true;save();renderPrompt()};e.addEventListener('input',fn);e.addEventListener('change',fn);}renderPrompt();
$('#copyPrompt').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(assemblePrompt());toast('Instruction copiée. Vous pouvez la tester dans votre outil IA habituel.')}catch(e){toast('La copie automatique est indisponible ; sélectionnez le texte dans le bloc pour le copier.')}});
$('#methodForm').addEventListener('submit',e=>{e.preventDefault();if(mFields.some(id=>(state.method[id]||'').trim().length<8)||!['mCheckFactual','mCheckScope','mCheckPrivacy'].every(k=>state.method[k]===true)){showFeedback('#methodFeedback','Remplissez les six éléments du brief (8 caractères minimum chacun) et cochez les trois vérifications.',true);return}state.completed.methode=true;save();showFeedback('#methodFeedback','Instruction enregistrée. Ce contrôle vérifie la structure et vos confirmations, pas la pertinence du résultat produit par une IA. Copiez-la et testez-la dans votre propre outil.');});
function renderBook(){const entries=$('#bookEntries');entries.replaceChildren();state.book.forEach((entry,i)=>{const block=document.createElement('article');block.className='book-entry';const fields=bookFields.map(key=>`<label class="field">${fieldLabels[key]}<textarea rows="${key==='steps'||key==='prompt'?4:2}" maxlength="2200" data-book-field="${key}" data-book-index="${i}" placeholder="À compléter"></textarea></label>`).join('');block.innerHTML=`<div class="book-header"><strong>FICHE ${String(i+1).padStart(2,'0')} / 10</strong><button type="button" data-remove="${i}" aria-label="Supprimer la fiche ${i+1}">Supprimer</button></div><div class="book-grid"><label class="field">Catégorie<select data-book-field="category" data-book-index="${i}"><option value="recherche">Recherche et vérification</option><option value="redaction">Rédaction et transformation</option><option value="documents">Documents et fichiers</option><option value="organisation">Organisation et préparation</option><option value="decision">Comparaison et décision</option><option value="autre">Autre</option></select></label><label class="check-line"><input type="checkbox" data-book-field="tested" data-book-index="${i}"><span>J'ai testé cette procédure sur un cas réel autorisé ou une simulation identifiée.</span></label>${fields}</div>`;block.querySelectorAll('[data-book-field]').forEach(el=>{const key=el.dataset.bookField;el.type==='checkbox'?el.checked=entry[key]===true:el.value=entry[key]||''});entries.append(block)});renderProgress()}
$('#bookEntries').addEventListener('input',e=>{const el=e.target;if(!el.hasAttribute('data-book-field'))return;const i=Number(el.dataset.bookIndex),key=el.dataset.bookField;if(!state.book[i])return;state.book[i][key]=el.type==='checkbox'?el.checked:el.value;save()});$('#bookEntries').addEventListener('change',e=>{const el=e.target;if(!el.hasAttribute('data-book-field'))return;const i=Number(el.dataset.bookIndex),key=el.dataset.bookField;if(!state.book[i])return;state.book[i][key]=el.type==='checkbox'?el.checked:el.value;save()});
$('#bookEntries').addEventListener('click',e=>{const button=e.target.closest('[data-remove]');if(!button)return;const index=Number(button.dataset.remove);if(!Number.isInteger(index))return;if(!confirm('Supprimer cette fiche de votre Playbook ?'))return;state.book.splice(index,1);save();renderBook();toast('Fiche supprimée.')});
$('#addBookEntry').addEventListener('click',()=>{if(state.book.length>=10){toast('Le Playbook est limité à dix fiches dans ce pilote.');return}state.book.push(sanitizeEntry({}));save();renderBook();$('#bookEntries .book-entry:last-child textarea')?.focus();});
function download(name,content,mime='text/plain'){const blob=new Blob([content],{type:mime+';charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function asMarkdown(){return '# Mon Playbook IA du quotidien — pilote IAgile\n\n_Généré à partir de mes réponses locales. Aucun certificat ni correction humaine._\n\n'+state.book.map((entry,i)=>'## '+(i+1)+'. '+(entry.name||'Processus sans nom')+'\n\n'+Object.entries(fieldLabels).filter(([k])=>k!=='name').map(([key,label])=>'**'+label+'**\n'+(entry[key]||'À compléter')+'\n').join('\n')+'\n**Catégorie :** '+entry.category+'\n**Test déclaré :** '+(entry.tested?'Oui':'Non')+'\n').join('\n---\n\n')}
$('#exportPlaybook').addEventListener('click',()=>{if(!state.book.length){toast('Ajoutez au moins une fiche avant de télécharger votre Playbook.');return}download('iagile-playbook-pilote.md',asMarkdown(),'text/markdown');toast('Playbook téléchargé au format Markdown.')});$('#printPlaybook').addEventListener('click',()=>{if(!state.book.length){toast('Votre Playbook est encore vide.');return}window.print()});
$('#exportProgress').addEventListener('click',()=>{download('iagile-pilote-sauvegarde.json',JSON.stringify({...state,updatedAt:new Date().toISOString()},null,2),'application/json');toast('Sauvegarde exportée localement.')});$('#importProgress').addEventListener('click',()=>$('#importFile').click());$('#importFile').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>1024*1024){toast('Fichier trop volumineux (1 Mo maximum).');return}try{const parsed=JSON.parse(await file.text());if(parsed.version!==1||!parsed.completed||!Array.isArray(parsed.book))throw Error('Invalid format');if(!confirm('Remplacer le travail actuel par cette sauvegarde ?'))return;state=hydrate(parsed);save();renderAll();navigate('accueil');toast('Sauvegarde importée.')}catch(err){toast('Ce fichier ne correspond pas à une sauvegarde V17 valide.')}});
$('#resetProgress').addEventListener('click',()=>{const d=$('#resetDialog');if(typeof d.showModal==='function')d.showModal();else if(confirm('Effacer toutes les réponses de ce navigateur ?'))reset()});$('#resetDialog').addEventListener('close',()=>{if($('#resetDialog').returnValue==='confirm')reset()});
function reset(){state=initial();try{localStorage.removeItem(KEY)}catch(e){}renderAll();navigate('accueil');toast('Le parcours a été réinitialisé.')}
function renderAll(){renderProfile();for(const id of cFields){const el=$('#'+id);if(el.type==='checkbox')el.checked=state.challenge[id]===true;else el.value=state.challenge[id]||''}updateGain();renderDiagnostic();$('#diagnosticHuman').value=state.diagnostic.human;$('#diagnosticRisk').checked=state.diagnostic.safe;for(const id of mFields.concat(['mCheckFactual','mCheckScope','mCheckPrivacy'])){const e=$('#'+id);if(e.type==='checkbox')e.checked=state.method[id]===true;else e.value=state.method[id]||''}renderPrompt();renderBook();['#challengeFeedback','#diagnosticFeedback','#methodFeedback'].forEach(sel=>$(sel).hidden=true);renderProgress()}
renderAll();const initialView=location.hash.slice(1);if(views.includes(initialView))navigate(initialView,false);else navigate('accueil',false);
if(!storageAvailable)toast('Le stockage local est indisponible : exportez vos réponses pour les garder.');
window.IAgilePilot={version:'17-pilot',views:views.slice(),getState:()=>structuredClone(state),navigate};
})();
