/* Exercices locaux IAgile : aucune donnée n'est envoyée au serveur. */
(()=>{'use strict';
const el=id=>document.getElementById(id),val=id=>el(id)?.value.trim()||'';
function show(id,s){const out=el(id);if(out){out.hidden=false;out.textContent=s;}}
function save(name,text){const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.querySelectorAll('[data-print]').forEach(b=>b.addEventListener('click',()=>print()));
const score=el('scorecard');if(score){score.addEventListener('submit',e=>{e.preventDefault();const ids=['before','prep','run','review','fix'];const n=ids.map(x=>Number(val(x)));if(ids.some(x=>val(x)==='')||n.some(x=>!Number.isFinite(x)||x<0)){show('score-result','Remplissez toutes les durées avec des nombres positifs ou zéro.');return;}const total=n.slice(1).reduce((a,b)=>a+b,0),gain=n[0]-total;const text='Tâche : '+(val('task')||'non précisée')+'\nTemps habituel : '+n[0]+' min\nTemps IA (préparation + génération + vérification + correction) : '+total+' min\nÉcart : '+gain+' min\n'+(gain>0?'Gain observé sur cet essai uniquement.':gain===0?'Pas de gain mesuré.':'Cette méthode a demandé plus de temps.')+'\nVérifiez la qualité avant de réutiliser.';show('score-result',text);el('save-score').hidden=false;el('save-score').onclick=()=>save('iagile-scorecard.txt',text);});}
const brief=el('brief');if(brief){brief.addEventListener('submit',e=>{e.preventDefault();const data=[['Objectif','goal'],['Public','audience'],['Navigation','journey'],['Rôle de la 3D','role'],['Version mobile','mobile'],['Alternative sans 3D','fallback']].map(([l,id])=>l+' : '+(val(id)||'à préciser')).join('\n\n');show('brief-result',data);el('save-brief').hidden=false;el('save-brief').onclick=()=>save('iagile-brief-3d.txt',data);});}
const checks=el('agent-checks');if(checks){checks.addEventListener('change',()=>{const boxes=[...checks.querySelectorAll('input[type="checkbox"]')];show('agent-result',boxes.filter(x=>x.checked).length+' / '+boxes.length+' points évalués. Ce diagnostic ne constitue pas une certification de fiabilité.');});}
})();